title: Kai's Robotics Portfolio
description: A portfolio of robotics and automation projects.
theme: jekyll-theme-minimal
avatar: "./images/github-pic.JPG" 
baseurl: "" # Leave blank unless deploying to a subfolder
url: "https://trungkhang111005.github.io" # Replace <your-username> with your GitHub username

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Navigation links (if needed)
# Uncomment and customize these if your theme supports a navigation bar
# navbar:
#   - name: "Home"
#     link: /
#   - name: "Projects"
#     link: /projects
#   - name: "Contact"
#     link: /contact

# Social links (if applicable)
social_links:
  - name: LinkedIn
    url: "https://www.linkedin.com/in/trung-khang-nguyen-900b86203"
  - name: GitHub
    url: "https://github.com/trungkhang111005"

# Optional: Analytics
# google_analytics: UA-XXXXXXXX-X
