remote_theme: "dracula/gh-pages"
title: Kai’s Projects Portfolio
description: Welcome to my GitHub portfolio! I am a passionate Mechatronics/Automation enthusiast with experience in automation equipment, computer vision, embedded systems, robotics simulation and 3D modelling. Below, you’ll find detailed information on my primary projects. Feel free to explore the projects and reach out with any questions or feedback.
